spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/sharedMap
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                default_batch_fetch_size: 100
            open-in-view: false
    messages:
        basename: messages
logging.level:
    org.hibernate.type: trace

server:
    servlet:
        session:
            tracking-modes: cookie
    error:
        include-binding-errors: always